# Generated by Django 4.2.7 on 2023-11-19 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cine', '0003_alter_cine_aforo_alter_cine_cantsalas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadSilla', models.PositiveIntegerField()),
                ('NumeroSala', models.CharField(max_length=7)),
                ('TamanioPantalla', models.CharField(max_length=30)),
                ('InclusividadSala', models.BooleanField(default=True, max_length=10)),
                ('TipoSala', models.CharField(choices=[('normal', 'Normal'), ('premiun', 'Premiun'), ('vip', 'Vip')], max_length=10)),
                ('EstadoSala', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], max_length=10)),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.cine')),
            ],
        ),
    ]
