# Generated by Django 4.2.7 on 2023-11-20 01:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0003_alter_cine_aforo_alter_cine_cantsalas_and_more'),
        ('Sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='CantidadSilla',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000000000000000)]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='InclusividadSala',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sala',
            name='NumeroSala',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000000000000000)]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='TamanioPantalla',
            field=models.CharField(choices=[('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('80', '80')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sala',
            name='cine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Cine.cine'),
        ),
    ]
