# Generated by Django 4.2.7 on 2023-11-20 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0003_alter_cine_aforo_alter_cine_cantsalas_and_more'),
        ('Sala', '0002_alter_sala_cantidadsilla_alter_sala_inclusividadsala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='cine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.cine'),
        ),
    ]
