# Generated by Django 4.2.7 on 2023-11-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=9)),
                ('cantSalas', models.IntegerField(max_length=3)),
                ('aforo', models.IntegerField(max_length=10)),
            ],
        ),
    ]
