# Generated by Django 4.2.7 on 2023-11-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='aforo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cine',
            name='cantSalas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cine',
            name='correo',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cine',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
