# Generated by Django 4.2.7 on 2023-11-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sala', '0001_initial'),
        ('Funcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sala.sala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcion',
            name='tipoFuncion',
            field=models.CharField(choices=[('3D', '3D'), ('2D', '2D')], max_length=10),
        ),
    ]
